In [1]:
import numpy as np
import gym, random, time
from IPython.display import clear_output

In [2]:
# Q-Table

env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Q-Learning Parameters

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [4]:
rewards_all_episodes = []

#Q-Learning algorithm

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation Threshold
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-Table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) +\
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #Exploration Rate Decay
    
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, " : ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-Table
print("\n\n********Q-Table********")
print(q_table)

********Average reward per thousand episodes********

1000  :  0.035000000000000024
2000  :  0.21000000000000016
3000  :  0.4110000000000003
4000  :  0.5470000000000004
5000  :  0.6340000000000005
6000  :  0.6500000000000005
7000  :  0.6710000000000005
8000  :  0.6920000000000005
9000  :  0.6800000000000005
10000  :  0.6970000000000005


********Q-Table********
[[0.57147765 0.52206973 0.52292257 0.51151984]
 [0.3012971  0.28606137 0.2903328  0.47724383]
 [0.43359953 0.29174997 0.27401809 0.26695642]
 [0.00848795 0.10155595 0.02603967 0.09247012]
 [0.59695328 0.36709419 0.45822353 0.29546183]
 [0.         0.         0.         0.        ]
 [0.23018827 0.08628727 0.40783748 0.0868339 ]
 [0.         0.         0.         0.        ]
 [0.33005226 0.40376757 0.45758213 0.63995393]
 [0.39276268 0.71916998 0.28494539 0.496598  ]
 [0.66176894 0.39181942 0.29562796 0.22732927]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48997931 0.57417688 0

In [5]:
for episode in range(3):
    state = env.reset()
    done = False
    print("****** Episode ", episode+1, "****\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through the hell!****")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
