In [1]:
import numpy as np
import gym, random, time
from IPython.display import clear_output

In [2]:
# Q-Table

env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Q-Learning Parameters

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [4]:
rewards_all_episodes = []

#Q-Learning algorithm

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation Threshold
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-Table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) +\
            learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #Exploration Rate Decay
    
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, " : ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-Table
print("\n\n********Q-Table********")
print(q_table)

********Average reward per thousand episodes********

1000  :  0.03900000000000003
2000  :  0.21800000000000017
3000  :  0.3870000000000003
4000  :  0.5300000000000004
5000  :  0.6230000000000004
6000  :  0.6730000000000005
7000  :  0.6810000000000005
8000  :  0.6880000000000005
9000  :  0.6500000000000005
10000  :  0.6650000000000005


********Q-Table********
[[0.55866117 0.46925131 0.4881427  0.46657196]
 [0.30284344 0.28407404 0.34007501 0.50062829]
 [0.38194547 0.37053648 0.42049685 0.45534226]
 [0.26432586 0.27329048 0.30403366 0.43305225]
 [0.5708004  0.33158443 0.38892574 0.24327926]
 [0.         0.         0.         0.        ]
 [0.30953815 0.10249697 0.14456748 0.08658877]
 [0.         0.         0.         0.        ]
 [0.43103002 0.38439786 0.42012161 0.59227959]
 [0.4254866  0.64155027 0.38652144 0.4587282 ]
 [0.55104377 0.44086542 0.34630569 0.37604395]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.59629801 0.56144454 0.